spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:defassio}:${DB_PASSWORD:caKJImx1YWrYJtLe}@webfluxcluster.zjmkrbz.mongodb.net/${DB_NAME:webflux}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux